FROM maven:3.9-eclipse-temurin-21 AS build
WORKDIR /app


COPY pom.xml ./pom.xml
COPY api-gateway ./api-gateway


RUN mvn -pl api-gateway -am clean package -DskipTests

FROM eclipse-temurin:21-jre-alpine
WORKDIR /app

COPY --from=build /app/api-gateway/target/*.jar app.jar

EXPOSE 9090

ENTRYPOINT ["java", "-jar", "app.jar"]
