spring.application.name=backend
server.port=${SERVER_PORT:9090}
spring.jackson.serialization.write-dates-as-timestamps=false

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/petclinic_auth_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
management.endpoints.web.exposure.include=health
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:true}
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

security.jwt.secret=${JWT_SECRET}
security.jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}
security.cookie.same-site=${SECURITY_COOKIE_SAMESITE:Strict}